apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: sealed-secrets-operator-helm
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: sealed-secrets-
  namespace: sealed-secrets
spec:
  targetNamespaces:
  - sealed-secrets