apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "springboot-tekton.fullname" . }}-el
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  triggers:
    - name: dev-cd-deploy-from-master
      interceptors:
        - cel:
            filter: >-
              body.repository.full_name == 'paolocarta/spring-rest-tekton-pipeline' &&
              body.ref.startsWith('refs/heads/master')
      bindings:
      - name: {{ include "springboot-tekton.fullname" . }}-tb
      template:
        name: {{ include "springboot-tekton.fullname" . }}-tt