apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
spec:
  destination:
    namespace: bookinfo
    server: 'https://kubernetes.default.svc'
  project: demolab
  source:
    path: 5-example-data/bookinfo
    repoURL: https://github.com/ekrunch/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-service-mesh
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - group: maistra.io
    jsonPointers:
    - /spec/members
    kind: ServiceMeshMemberRoll
  project: demolab
  source:
    path: 5-example-data/servicemesh
    repoURL: https://github.com/ekrunch/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
